# Generated by Django 5.1.3 on 2024-11-19 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Process'), (2, 'Complated'), (3, 'Cancelled')], default=0)),
                ('priority', models.IntegerField(choices=[(0, 'Lowest'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Highest')], default=2)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=202)),
                ('content', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
